# Generated by Django 5.2.15 on 2026-06-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='مقدم الشكوى/المقترح')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('subject', models.CharField(max_length=255, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='التفاصيل')),
                ('status', models.CharField(choices=[('new', 'جديدة'), ('in_progress', 'قيد المراجعة'), ('resolved', 'تم الحل')], default='new', max_length=50, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقديم')),
            ],
            options={
                'verbose_name': 'شكوى/مقترح',
                'verbose_name_plural': 'الشكاوى والمقترحات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouncilMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('position', models.CharField(max_length=100, verbose_name='المنصب (مثال: نقيب المحامين)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='council/', verbose_name='الصورة')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'عضو مجلس',
                'verbose_name_plural': 'مجلس النقابة',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الخبر')),
                ('content', models.TextField(verbose_name='محتوى الخبر')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='صورة الخبر')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاريخ النشر')),
                ('is_published', models.BooleanField(default=True, verbose_name='منشور')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'الأخبار والقرارات',
                'ordering': ['-date'],
            },
        ),
    ]
