# Generated by Django 5.2.15 on 2026-06-16 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='السؤال')),
                ('answer', models.TextField(verbose_name='الإجابة')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'سؤال شائع',
                'verbose_name_plural': 'الأسئلة الشائعة',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='اسم الخدمة')),
                ('description', models.TextField(verbose_name='وصف الخدمة')),
                ('icon', models.CharField(default='fa-solid fa-circle-check', max_length=100, verbose_name='أيقونة FontAwesome')),
                ('url', models.CharField(blank=True, max_length=200, verbose_name='رابط الخدمة')),
                ('target', models.CharField(choices=[('all', 'الجميع'), ('lawyer', 'المحامون فقط'), ('citizen', 'المواطنون فقط')], default='all', max_length=20, verbose_name='الفئة المستهدفة')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'خدمة',
                'verbose_name_plural': 'الخدمات الإلكترونية',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(choices=[('complaint', 'شكوى'), ('suggestion', 'مقترح'), ('inquiry', 'استفسار')], default='complaint', max_length=20, verbose_name='نوع الطلب'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('news', 'خبر'), ('decision', 'قرار'), ('announcement', 'إعلان'), ('event', 'فعالية')], default='news', max_length=20, verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='name',
            field=models.CharField(max_length=255, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('new', 'جديدة'), ('in_progress', 'قيد المراجعة'), ('resolved', 'تم الحل')], default='new', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='councilmember',
            name='position',
            field=models.CharField(max_length=100, verbose_name='المنصب'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255, verbose_name='العنوان'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('citizen', 'مواطن'), ('lawyer', 'محامٍ')], default='citizen', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('national_id', models.CharField(blank=True, max_length=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملف المستخدم',
                'verbose_name_plural': 'ملفات المستخدمين',
            },
        ),
    ]
