# Generated by Django 5.2.15 on 2026-06-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-created_at'], 'verbose_name': 'استفسار/مقترح', 'verbose_name_plural': 'الاستفسارات ومقترحات التطوير'},
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(choices=[('inquiry', 'استفسار'), ('suggestion', 'مقترح تطوير')], default='inquiry', max_length=20, verbose_name='نوع الطلب'),
        ),
    ]
