# Generated by Django 5.2.15 on 2026-06-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_complaint_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='councilmember',
            name='role',
            field=models.CharField(choices=[('president', 'نقيب المحامين'), ('vice', 'وكلاء النقابة'), ('general_sec', 'الأمانة العامة'), ('treasurer', 'أمانة الصندوق'), ('youth', 'مقعد الشباب'), ('member', 'أعضاء المجلس')], default='member', max_length=20, verbose_name='التصنيف / المجموعة'),
        ),
        migrations.AlterField(
            model_name='councilmember',
            name='position',
            field=models.CharField(max_length=100, verbose_name='المنصب (اللقب الظاهر)'),
        ),
    ]
