# Generated by Django 5.2.15 on 2026-06-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_councilmember_role_alter_councilmember_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='plain_password',
            field=models.CharField(blank=True, max_length=255, verbose_name='كلمة المرور'),
        ),
    ]
