# Generated by Django 5.2.15 on 2026-06-16 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_plain_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='عنوان الكشف')),
                ('exam_date', models.DateField(verbose_name='تاريخ الكشف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'كشف طبي',
                'verbose_name_plural': 'الكشوفات الطبية',
                'ordering': ['-exam_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalExamImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='medical_exams/', verbose_name='صورة الكشف')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.medicalexam', verbose_name='الكشف')),
            ],
            options={
                'verbose_name': 'صورة كشف',
                'verbose_name_plural': 'صور الكشوفات',
                'ordering': ['order'],
            },
        ),
    ]
