# Generated by Django 5.2.15 on 2026-06-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_medicalexam_medicalexamimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='عنوان المحاضرة أو الدورة')),
                ('description', models.TextField(blank=True, verbose_name='التفاصيل')),
                ('lecture_date', models.DateField(blank=True, null=True, verbose_name='تاريخ المحاضرة')),
                ('video_link', models.URLField(blank=True, verbose_name='رابط فيديو (يوتيوب وغيرها)')),
                ('file', models.FileField(blank=True, null=True, upload_to='institute_files/', verbose_name='ملف مرفق (PDF, Word)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'محاضرة معهد',
                'verbose_name_plural': 'محاضرات المعهد',
                'ordering': ['-created_at'],
            },
        ),
    ]
