# Generated by Django 5.2.15 on 2026-06-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_institutelecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='institute_registration_link',
            field=models.URLField(blank=True, null=True, verbose_name='رابط التقديم في معهد المحاماة (مثل Google Form)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='is_institute_open',
            field=models.BooleanField(default=False, verbose_name='تفعيل زر التقديم لمعهد المحاماة'),
        ),
    ]
