# Generated by Django 5.2.15 on 2026-06-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sitesettings_institute_registration_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutelecture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='institute_news/', verbose_name='صورة الخبر'),
        ),
        migrations.AlterField(
            model_name='institutelecture',
            name='description',
            field=models.TextField(blank=True, verbose_name='نص الخبر'),
        ),
        migrations.AlterField(
            model_name='institutelecture',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='institute_files/', verbose_name='ملف مرفق'),
        ),
        migrations.AlterField(
            model_name='institutelecture',
            name='lecture_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الخبر'),
        ),
        migrations.AlterField(
            model_name='institutelecture',
            name='title',
            field=models.CharField(max_length=500, verbose_name='عنوان الخبر'),
        ),
        migrations.AlterField(
            model_name='institutelecture',
            name='video_link',
            field=models.URLField(blank=True, verbose_name='رابط إضافي'),
        ),
    ]
