# Generated by Django 4.2.27 on 2026-06-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_institutelecture_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='اسم الملف')),
                ('data', models.BinaryField(verbose_name='بيانات الملف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ملف قاعدة بيانات',
                'verbose_name_plural': 'ملفات قاعدة البيانات',
            },
        ),
    ]
