# Generated by Django 4.2.27 on 2026-06-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_databasefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='in_slider',
            field=models.BooleanField(default=True, verbose_name='عرض في السلايدر الرئيسي'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='صورة الخبر'),
        ),
    ]
