# Generated by Django 4.2.27 on 2026-06-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_news_in_slider_alter_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='is_under_maintenance',
            field=models.BooleanField(default=False, verbose_name='وضع الصيانة (قيد التطوير)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='موعد انتهاء التطوير (للعد التنازلي)'),
        ),
    ]
