# Generated by Django 4.2.27 on 2026-06-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sitesettings_is_under_maintenance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='syndicate_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='رقم القيد'),
        ),
    ]
