# Generated by Django 4.2.27 on 2026-07-05 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_userprofile_syndicate_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=64, unique=True, verbose_name='مفتاح الجلسة')),
                ('user_name', models.CharField(max_length=100, verbose_name='اسم المستخدم')),
                ('status', models.CharField(choices=[('waiting', 'في الانتظار'), ('active', 'نشطة'), ('ended', 'منتهية')], default='waiting', max_length=10, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'جلسة محادثة',
                'verbose_name_plural': 'جلسات المحادثة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='councilmember',
            name='role',
            field=models.CharField(choices=[('president', 'نقيب المحامين'), ('vice', 'وكلاء النقابة'), ('general_sec', 'الأمانة العامة'), ('treasurer', 'أمانة الصندوق'), ('youth', 'عضو الشباب'), ('member', 'أعضاء المجلس')], default='member', max_length=20, verbose_name='التصنيف / المجموعة'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'مستخدم'), ('admin', 'مسئول'), ('system', 'نظام')], max_length=10)),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.chatsession')),
            ],
            options={
                'verbose_name': 'رسالة محادثة',
                'verbose_name_plural': 'رسائل المحادثة',
                'ordering': ['created_at'],
            },
        ),
    ]
