# Generated by Django 4.2.27 on 2026-07-11 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_chatsession_alter_councilmember_role_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_gallery/', verbose_name='صورة إضافية')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.news', verbose_name='الخبر')),
            ],
            options={
                'verbose_name': 'صورة إضافية للخبر',
                'verbose_name_plural': 'صور الخبر الإضافية',
                'ordering': ['order'],
            },
        ),
    ]
