# Generated by Django 4.2.27 on 2026-07-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_newsimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان الكتاب')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='اسم المؤلف')),
                ('description', models.TextField(blank=True, verbose_name='نبذة عن الكتاب')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='library/books/', verbose_name='صورة الغلاف')),
                ('file', models.FileField(blank=True, null=True, upload_to='library/books/files/', verbose_name='ملف PDF')),
                ('external_url', models.URLField(blank=True, verbose_name='رابط خارجي')),
                ('is_active', models.BooleanField(default=True, verbose_name='منشور')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'كتاب قانوني',
                'verbose_name_plural': 'الكتب القانونية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LibraryContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='اسم النموذج')),
                ('category', models.CharField(choices=[('sale', 'عقود البيع والشراء'), ('rent', 'عقود الإيجار'), ('work', 'عقود العمل'), ('company', 'عقود الشركات'), ('proxy', 'توكيلات'), ('divorce', 'أحوال شخصية'), ('criminal', 'مذكرات جنائية'), ('civil', 'مذكرات مدنية'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='التصنيف')),
                ('description', models.TextField(blank=True, verbose_name='وصف النموذج')),
                ('file', models.FileField(blank=True, null=True, upload_to='library/contracts/', verbose_name='ملف النموذج (PDF / Word)')),
                ('is_active', models.BooleanField(default=True, verbose_name='منشور')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نموذج عقد',
                'verbose_name_plural': 'نماذج العقود',
                'ordering': ['category', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LibraryJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان العدد')),
                ('issue_number', models.CharField(blank=True, max_length=50, verbose_name='رقم العدد')),
                ('description', models.TextField(blank=True, verbose_name='وصف العدد')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='library/journals/', verbose_name='صورة الغلاف')),
                ('file', models.FileField(blank=True, null=True, upload_to='library/journals/files/', verbose_name='ملف PDF')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإصدار')),
                ('is_active', models.BooleanField(default=True, verbose_name='منشور')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'عدد المجلة',
                'verbose_name_plural': 'المجلة الإلكترونية',
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LibraryLegislation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='العنوان')),
                ('category', models.CharField(choices=[('law', 'قانون'), ('decree', 'مرسوم / لائحة'), ('ruling', 'حكم قضائي'), ('circular', 'منشور / تعميم'), ('treaty', 'اتفاقية دولية')], default='law', max_length=20, verbose_name='التصنيف')),
                ('number', models.CharField(blank=True, max_length=100, verbose_name='رقم القانون / الحكم')),
                ('year', models.CharField(blank=True, max_length=10, verbose_name='سنة الإصدار')),
                ('description', models.TextField(blank=True, verbose_name='نبذة')),
                ('file', models.FileField(blank=True, null=True, upload_to='library/legislation/', verbose_name='ملف PDF')),
                ('external_url', models.URLField(blank=True, verbose_name='رابط خارجي')),
                ('is_active', models.BooleanField(default=True, verbose_name='منشور')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تشريع / حكم',
                'verbose_name_plural': 'بوابة التشريعات والأحكام',
                'ordering': ['-year', '-created_at'],
            },
        ),
    ]
