# Generated by Django 4.2.27 on 2026-07-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_librarybook_librarycontract_libraryjournal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarycontract',
            name='external_url',
            field=models.URLField(blank=True, verbose_name='رابط خارجي'),
        ),
        migrations.AddField(
            model_name='libraryjournal',
            name='external_url',
            field=models.URLField(blank=True, verbose_name='رابط خارجي'),
        ),
    ]
