# Generated by Django 4.2.27 on 2026-07-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_librarycontract_external_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarybook',
            name='external_url',
            field=models.URLField(blank=True, max_length=800, verbose_name='رابط خارجي'),
        ),
        migrations.AlterField(
            model_name='librarycontract',
            name='external_url',
            field=models.URLField(blank=True, max_length=800, verbose_name='رابط خارجي'),
        ),
        migrations.AlterField(
            model_name='libraryjournal',
            name='external_url',
            field=models.URLField(blank=True, max_length=800, verbose_name='رابط خارجي'),
        ),
        migrations.AlterField(
            model_name='librarylegislation',
            name='external_url',
            field=models.URLField(blank=True, max_length=800, verbose_name='رابط خارجي'),
        ),
    ]
