# Generated by Django 4.2.27 on 2026-07-11 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_increase_external_url_length'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LibraryJournal',
        ),
    ]
