# Generated by Django 4.2.27 on 2026-07-11 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_libraryjournal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LibraryLegislation',
        ),
    ]
