# Generated by Django 4.2.27 on 2026-07-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_librarylegislation'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarycontract',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='library/contracts/covers/', verbose_name='صورة الغلاف'),
        ),
    ]
