# Generated by Django 4.2.27 on 2026-07-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_librarycontract_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarybook',
            name='downloads_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد التنزيلات'),
        ),
        migrations.AddField(
            model_name='librarybook',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات'),
        ),
        migrations.AddField(
            model_name='librarycontract',
            name='downloads_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد التنزيلات'),
        ),
        migrations.AddField(
            model_name='librarycontract',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات'),
        ),
        migrations.AddField(
            model_name='news',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='total_visits',
            field=models.PositiveIntegerField(default=0, verbose_name='إجمالي زيارات الموقع'),
        ),
    ]
