# Generated by Django 4.2.27 on 2026-07-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_librarybook_downloads_count_librarybook_views_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='is_inquiry_open',
            field=models.BooleanField(default=True, verbose_name='تفعيل قسم الاستعلام في الموقع'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='is_institute_open',
            field=models.BooleanField(default=False, verbose_name='فتح التسجيل لمعهد المحاماة'),
        ),
    ]
