# Generated by Django 4.2.27 on 2026-07-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_is_inquiry_open_toggle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_type', models.CharField(max_length=50, verbose_name='النظام (أرشيف/شكاوى/شهادات)')),
                ('inquiry_number', models.CharField(max_length=50, verbose_name='رقم الاستعلام')),
                ('response_data', models.JSONField(verbose_name='بيانات الرد المحفوظة')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'استعلام مؤرشف (Cache)',
                'verbose_name_plural': 'الاستعلامات المؤرشفة (Cache)',
                'unique_together': {('system_type', 'inquiry_number')},
            },
        ),
    ]
