# Generated by Django 4.2.27 on 2026-07-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_cached_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='slider_style',
            field=models.CharField(choices=[('classic', 'الكلاسيكي (التصميم الحالي)'), ('fullwidth', 'صور كاملة (طراز نقابة المحامين المصرية)')], default='classic', max_length=20, verbose_name='نوع السلايدر الرئيسي'),
        ),
    ]
