# Generated by Django 5.2.15 on 2026-06-16 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم الرباعي')),
                ('registration_number', models.CharField(max_length=50, unique=True, verbose_name='رقم القيد')),
                ('national_id', models.CharField(max_length=14, unique=True, verbose_name='الرقم القومي')),
                ('degree', models.CharField(choices=[('1', 'جدول عام'), ('2', 'ابتدائي'), ('3', 'استئناف'), ('4', 'نقض')], max_length=50, verbose_name='درجة القيد')),
                ('status', models.CharField(choices=[('active', 'مشتغل'), ('inactive', 'غير مشتغل'), ('suspended', 'موقوف')], default='active', max_length=50, verbose_name='حالة العضوية')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='lawyers/', verbose_name='الصورة الشخصية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم')),
            ],
            options={
                'verbose_name': 'محامي',
                'verbose_name_plural': 'المحامين',
                'ordering': ['-created_at'],
            },
        ),
    ]
